import type { Metadata } from 'next'
import Link from 'next/link'
import { PremiumSiteHeader } from '@/components/premium-site-header'
import { PremiumSiteFooter } from '@/components/premium-site-footer'
import { EditorialIntro } from '@/components/editorial-intro'
export const metadata: Metadata = { title: 'About MarketplaceBeta', description: 'Why MarketplaceBeta combines ecommerce news discovery, practical guides, and operating tools.', alternates: { canonical: '/about' } }
export default function AboutPage() {
  return <div className="min-h-screen bg-background"><PremiumSiteHeader /><main className="mx-auto site-width px-4 py-10 sm:px-6"><EditorialIntro eyebrow="About MarketplaceBeta" title="Commerce, with operating context." description="MarketplaceBeta helps ecommerce operators discover developments, investigate costs, and work through business decisions." />
    <section className="mx-auto mt-8 max-w-4xl rounded-2xl border border-border bg-card p-6 sm:p-9 editorial-elevated space-y-6"><h2 className="text-2xl font-bold">Built around the next decision</h2><p>Our focus is marketplace selling, fulfillment, advertising, profitability, and the systems that connect channels. The site brings together source-linked news, a research archive, educational guides, and scenario tools.</p><p>News aggregation and AI-assisted summaries help organize a large volume of information. They do not replace original reporting, current platform documentation, or your own operating data. MarketplaceBeta is not affiliated with or endorsed by the marketplaces it covers.</p><h2 className="text-2xl font-bold">What you can use today</h2><ul className="list-disc space-y-3 pl-6"><li><Link className="text-primary underline" href="/guides">Operator guides and free worksheets</Link> explain decisions with hypothetical examples.</li><li><Link className="text-primary underline" href="/tools">Scenario tools</Link> help explore assumptions; modeled signals are labeled.</li><li><Link className="text-primary underline" href="/articles">The archive</Link> lets you follow a topic back to its sources.</li></ul><h2 className="text-2xl font-bold">Questions and corrections</h2><p>Send the page URL, the disputed statement, and supporting evidence to <a className="text-primary underline" href="mailto:hello@marketplacebeta.com?subject=MarketplaceBeta%20correction">hello@marketplacebeta.com</a>. Please do not include private customer information.</p><Link className="inline-block font-semibold text-primary" href="/editorial-policy">Read our editorial method →</Link></section>
  </main><PremiumSiteFooter /></div>
}
