import type { Metadata } from 'next'
import { PremiumSiteHeader } from '@/components/premium-site-header'
import { PremiumSiteFooter } from '@/components/premium-site-footer'
import { EditorialIntro } from '@/components/editorial-intro'
export const metadata: Metadata = { title: 'Editorial method and corrections | MarketplaceBeta', description: 'How MarketplaceBeta uses sources, automated curation, AI summaries, examples, and corrections.', alternates: { canonical: '/editorial-policy' } }
export default function EditorialPolicyPage() {
  const sections = [
    ['Source-linked discovery', 'Aggregated stories identify the source and link to the original coverage. Original publishers retain responsibility for their reporting. Follow the source to check context, publication dates, and subsequent corrections. Where a claim concerns a fee, rule, or platform feature, use current official documentation before acting.'],
    ['Automated filtering has limits', 'We use relevance signals, explicit topic exclusions, and headline similarity to reduce irrelevant and repeated coverage. These controls are imperfect. A high-impact label reflects an automated assessment of possible business relevance; it is not a fact-check or an endorsement. Historical stories can remain useful, but their dates matter.'],
    ['How AI is used', 'AI assists with classification, summaries, briefing synthesis, and educational drafting. Automated news is not represented as individually reviewed by a human operator. Generated explanations can contain omissions, incorrect dates, or unsupported conclusions. Check the linked evidence, especially before changing spending, inventory, or compliance decisions.'],
    ['Guides, calculations, and modeled data', 'Our operator guides distinguish hypothetical examples from reported facts, identify assumptions, and provide sources for platform concepts. Examples are educational calculations, not real seller case studies. Tools are estimates; keyword and product preview signals are not measured demand. An updated date means that page was revised, not that every external source is continuously verified.'],
    ['Corrections', 'To flag an error, email hello@marketplacebeta.com with the page URL, the exact statement, and a reliable supporting source. Substantive guide changes should update the page date and explain the corrected assumption where relevant. No response time is guaranteed.'],
    ['Commercial relationships', 'Any future paid placement or affiliate recommendation should be labeled where readers encounter it. Commercial placement must not be presented as an independent editorial ranking or as evidence that a product is suitable for every business.'],
  ]
  return <div className="min-h-screen bg-background"><PremiumSiteHeader /><main className="mx-auto max-w-4xl px-4 py-10 sm:px-6"><EditorialIntro eyebrow="Our editorial method" title="Know where the information comes from." description="Our approach to sources, automation, educational examples, and corrections. Updated October 9, 2026." /><article className="mt-8 rounded-2xl border border-border bg-card p-6 sm:p-9 editorial-elevated">{sections.map(([title,body]) => <section key={title} className="mb-8 last:mb-0"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-4 leading-8 text-muted-foreground">{body}</p></section>)}</article></main><PremiumSiteFooter /></div>
}
