'use client'
import { useState } from 'react'
import { ArrowUpRight, Search } from 'lucide-react'
import { MANUFACTURING_TOPICS, MANUFACTURING_PROCESSES, MANUFACTURING_PROMPTS, filterManufacturingStories, type ManufacturingSnapshot } from '@/lib/manufacturing'
const date = (value: string) => new Intl.DateTimeFormat('en-US', {month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(value))
export function ManufacturingNews({ snapshot }: { snapshot: ManufacturingSnapshot }) {
  const [query,setQuery] = useState(''), [topic,setTopic] = useState(''), [process,setProcess] = useState(''), [days,setDays] = useState(30), [limit,setLimit] = useState(12)
  const stories = filterManufacturingStories(snapshot.stories, {query,topic,process,days}, Date.parse(snapshot.checkedAt))
  const unavailable = snapshot.sources.every(source => !source.available)
  return <section id="manufacturing-news" className="scroll-mt-44" aria-labelledby="manufacturing-news-title">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="editorial-eyebrow">The manufacturing news desk</p><h2 id="manufacturing-news-title" className="mt-2 text-3xl font-bold sm:text-4xl">What changed. Where to look next.</h2></div><p aria-live="polite" className="rounded-full border border-border bg-card px-4 py-2 text-sm font-semibold">{stories.length} reports</p></div>
    <p className="mt-4 max-w-3xl leading-7 text-muted-foreground">Dated headlines from selected publishers, newest first. Topic tags are automated; the questions below are research prompts, not findings about demand or profitability.</p>
    <div className="editorial-elevated mt-6 grid gap-4 rounded-2xl border border-border bg-card p-5 sm:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr_1fr]">
      <label className="text-sm font-semibold">Search this desk<div className="relative mt-2"><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12)}} placeholder="Machine, material, brand…" className="w-full min-w-0 rounded-lg border border-border bg-background py-3 pl-9 pr-3 text-base"/></div></label>
      <label className="text-sm font-semibold">Topic<select value={topic} onChange={e=>{setTopic(e.target.value);setLimit(12)}} className="mt-2 block w-full rounded-lg border border-border bg-background px-3 py-3 text-base"><option value="">All topics</option>{MANUFACTURING_TOPICS.map(t=><option key={t}>{t}</option>)}</select></label>
      <label className="text-sm font-semibold">Process<select value={process} onChange={e=>{setProcess(e.target.value);setLimit(12)}} className="mt-2 block w-full rounded-lg border border-border bg-background px-3 py-3 text-base"><option value="">All processes</option>{MANUFACTURING_PROCESSES.map(p=><option key={p}>{p}</option>)}</select></label>
      <label className="text-sm font-semibold">Published<select value={days} onChange={e=>{setDays(Number(e.target.value));setLimit(12)}} className="mt-2 block w-full rounded-lg border border-border bg-background px-3 py-3 text-base"><option value={7}>Past 7 days</option><option value={30}>Past 30 days</option><option value={90}>Past 90 days</option></select></label>
    </div>
    {!stories.length ? <div className="mt-6 rounded-2xl border border-dashed border-border bg-card p-8"><h3 className="text-xl font-bold">{unavailable ? 'Source coverage is temporarily unavailable.' : 'No reports match this view.'}</h3><p className="mt-3 text-muted-foreground">{unavailable ? 'Visit the source directory below or return later. Missing coverage does not mean the market is quiet.' : 'Try a longer period or another topic. Publisher feeds contain a limited selection of recent posts.'}</p><button type="button" onClick={()=>{setQuery('');setTopic('');setProcess('');setDays(90)}} className="mt-5 font-semibold text-primary underline">Show all available coverage</button></div> : <div className="mt-7 grid items-stretch gap-6 md:grid-cols-2 xl:grid-cols-3">{stories.slice(0,limit).map(story=><article key={story.id} className="editorial-elevated editorial-lift flex min-w-0 flex-col overflow-hidden rounded-2xl border border-border bg-card"><div className="h-1.5 bg-gradient-to-r from-blue-600 via-cyan-500 to-teal-400"/><div className="flex flex-1 flex-col p-6 sm:p-7"><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-md bg-blue-500/10 px-2.5 py-1.5 text-blue-700 dark:text-blue-200">{story.topic}</span><span className="rounded-md bg-secondary px-2.5 py-1.5 text-muted-foreground">{story.process}</span></div><h3 className="mt-5 text-xl font-bold leading-snug sm:text-2xl"><a href={story.url} target="_blank" rel="noopener noreferrer" className="hover:text-primary">{story.title}</a></h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{story.sourceName} · {story.sourceKind}<br/><time dateTime={story.publishedAt}>{date(story.publishedAt)}</time></p><div className="mb-6 mt-5 rounded-xl border border-border bg-secondary/40 p-4"><p className="text-xs font-bold uppercase tracking-wider text-primary">Operator check</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{MANUFACTURING_PROMPTS[story.topic]}</p></div><a href={story.url} target="_blank" rel="noopener noreferrer" className="mt-auto inline-flex items-center gap-2 text-sm font-bold text-primary">Read the original report<ArrowUpRight className="h-4 w-4"/></a></div></article>)}</div>}
    {stories.length>limit && <button type="button" onClick={()=>setLimit(n=>n+12)} className="mt-7 rounded-lg border border-border bg-card px-6 py-3 font-semibold">Show more reports</button>}
  </section>
}
