import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowDown, ArrowUpRight, Box, CalendarDays, Cpu, Layers3, MoveUpRight, Wrench } from 'lucide-react'
import { PremiumSiteHeader } from '@/components/premium-site-header'
import { PremiumSiteFooter } from '@/components/premium-site-footer'
import { ManufacturingNews } from '@/components/manufacturing-news'
import { ResourceLink } from '@/components/resource-link'
import { loadManufacturingSnapshot } from '@/lib/manufacturing-data'
import { MANUFACTURING_SOURCES, upcomingManufacturingEvents } from '@/lib/manufacturing'
export const dynamic = 'force-dynamic'
export const metadata: Metadata = {
  title: 'Desktop Manufacturing News & Events | MarketplaceBeta',
  description: 'Follow 3D printing, desktop CNC, laser fabrication, materials, software, and manufacturing business news. Explore sources, events, and the MeshNomics companion.',
  alternates: { canonical: 'https://marketplacebeta.com/desktop-manufacturing' },
  openGraph: { title: 'The Desktop Manufacturing Economy | MarketplaceBeta', description: 'News, context, and next questions for the people making things.', url: 'https://marketplacebeta.com/desktop-manufacturing', type: 'website' },
}
const formatDate = (date: string) => new Intl.DateTimeFormat('en-US', {month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(date))
const resourceLinks = [
  { name: 'Printables', url: 'https://www.printables.com/', detail: 'Design discovery. Check each model’s license and any merchant terms before selling prints.' },
  { name: 'MakerWorld', url: 'https://makerworld.com/', detail: 'Models and maker programs. Popularity is an idea signal, not evidence of purchases or permission to sell.' },
  { name: 'OrcaSlicer releases', url: 'https://github.com/OrcaSlicer/OrcaSlicer/releases', detail: 'Official release notes. Check supported versions and validate changes before updating production machines.' },
  { name: 'Carbide 3D community', url: 'https://community.carbide3d.com/', detail: 'Desktop CNC operator discussions. Community experience is useful context, not a measured failure rate.' },
]
export default async function DesktopManufacturingPage() {
  const snapshot = await loadManufacturingSnapshot()
  const available = snapshot.sources.filter(source=>source.available).length
  const events = upcomingManufacturingEvents(Date.now())
  const latest = snapshot.stories[0]
  return <div className="min-h-screen bg-background"><PremiumSiteHeader active="manufacturing" />
    <main className="mx-auto site-width px-4 py-10 sm:px-6">
      <section className="relative overflow-hidden rounded-3xl border border-slate-800 bg-slate-950 p-7 text-white editorial-elevated sm:p-10 lg:p-14">
        <div aria-hidden="true" className="pointer-events-none absolute -right-32 -top-40 h-[32rem] w-[32rem] rounded-full bg-cyan-500/15 blur-3xl"/>
        <div className="relative grid items-center gap-10 lg:grid-cols-[1.3fr_1fr]">
          <div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300">A new desk at MarketplaceBeta</p><h1 className="mt-5 text-[clamp(1.75rem,8vw,2.25rem)] font-bold leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">The desktop<br/>manufacturing<br/><span className="text-cyan-300">economy.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">News, information, and perspective for the people turning small machines into real businesses.</p><div className="mt-5 flex flex-wrap gap-2 text-sm font-semibold">{['3D printing','Desktop CNC','Laser & fabrication'].map(label=><span key={label} className="rounded-full border border-white/15 bg-white/5 px-3 py-2">{label}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><a href="#manufacturing-news" className="inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-200">Explore the news<ArrowDown className="h-4 w-4"/></a><a href="#manufacturing-events" className="rounded-lg border border-white/25 px-5 py-3 font-semibold hover:bg-white/10">Find an event</a></div></div>
          <div className="grid gap-4"><div className="rounded-2xl border border-white/15 bg-white/[.07] p-6 shadow-xl"><div className="flex items-center justify-between"><Layers3 className="h-8 w-8 text-cyan-300"/><span className="text-xs font-bold uppercase tracking-widest text-slate-400">01 / Discover</span></div><h2 className="mt-5 text-2xl font-bold">Find the change that matters.</h2><p className="mt-3 leading-7 text-slate-300">Equipment, materials, software, designs, and the business of making.</p></div><div className="ml-0 rounded-2xl border border-cyan-300/30 bg-gradient-to-br from-blue-700 to-cyan-800 p-6 shadow-xl sm:ml-8"><div className="flex items-center justify-between"><Box className="h-8 w-8 text-cyan-100"/><span className="text-xs font-bold uppercase tracking-widest text-cyan-100">02 / Evaluate</span></div><h2 className="mt-5 text-2xl font-bold">Turn an idea into a question.</h2><p className="mt-3 leading-7 text-blue-100">What would this change in your costs, capacity, product mix, or customer offer?</p></div></div>
        </div>
      </section>
      <dl className="my-8 grid gap-4 sm:grid-cols-3"><div className="editorial-elevated rounded-2xl border border-border bg-card p-6"><dt className="text-sm text-muted-foreground">Reports available · past 90 days</dt><dd className="mt-2 text-3xl font-bold tabular-nums">{snapshot.stories.length}</dd></div><div className="editorial-elevated rounded-2xl border border-border bg-card p-6"><dt className="text-sm text-muted-foreground">Publisher feeds available</dt><dd className="mt-2 text-3xl font-bold tabular-nums">{available}<span className="text-xl text-muted-foreground"> / {MANUFACTURING_SOURCES.length}</span></dd></div><div className="editorial-elevated rounded-2xl border border-border bg-card p-6"><dt className="text-sm text-muted-foreground">Newest report published</dt><dd className="mt-2 text-2xl font-bold">{latest ? formatDate(latest.publishedAt) : 'Unavailable'}</dd></div></dl>
      <p className="mb-10 text-sm leading-6 text-muted-foreground">Source snapshot checked {formatDate(snapshot.checkedAt)} at {new Date(snapshot.checkedAt).toISOString().slice(11,16)} UTC. Source checks refresh on visits after 30 minutes. Feeds are selective; counts describe this desk’s coverage, not market size or growth.</p>
      <ManufacturingNews snapshot={snapshot}/>
      <section className="my-12 grid gap-6 lg:grid-cols-[1.35fr_1fr]" aria-labelledby="manufacturing-business-title">
        <div className="editorial-elevated rounded-2xl border border-border bg-card p-7 sm:p-9"><p className="editorial-eyebrow">The operator lens</p><h2 id="manufacturing-business-title" className="mt-3 text-3xl font-bold">Interesting news.<br/>Better business questions.</h2><div className="mt-7 space-y-6">{[
          {icon:Box,title:'Product opportunity',text:'Use a new application or design trend to form a testable idea. Validate buyer intent, competition, and commercial rights before committing stock.'},
          {icon:Cpu,title:'Capacity & workflow',text:'Compare real job throughput, operator time, maintenance, and failure rates with your own queue before buying another machine.'},
          {icon:Wrench,title:'Cost & contribution',text:'Bring material waste, post-processing, labor, packaging, marketplace fees, and returns into the same per-order calculation.'},
        ].map(item=><div key={item.title} className="flex items-start gap-4"><item.icon className="mt-1 h-6 w-6 shrink-0 text-primary"/><div><h3 className="text-lg font-bold">{item.title}</h3><p className="mt-2 leading-7 text-muted-foreground">{item.text}</p></div></div>)}</div><Link href="/guides/product-profitability" className="mt-7 inline-flex items-center gap-2 font-bold text-primary">Work through your product economics<MoveUpRight className="h-4 w-4"/></Link></div>
        <div className="editorial-elevated flex flex-col rounded-2xl border border-blue-700 bg-gradient-to-br from-blue-700 to-slate-950 p-7 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-200">Meet the companion</p><h2 className="mt-5 text-4xl font-bold">MeshNomics</h2><p className="mt-5 text-xl font-semibold leading-8">Your next idea deserves a closer look.</p><p className="mt-4 leading-8 text-blue-100">Explore our companion desktop manufacturing site as you research a product, machine, or business idea.</p><ResourceLink event="manufacturing_meshnomics_click" resource="desktop-manufacturing-desk" href="https://www.meshnomics.com/?utm_source=marketplacebeta&utm_medium=referral&utm_campaign=desktop_manufacturing_desk" target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center justify-center gap-2 rounded-lg bg-white px-5 py-4 font-bold text-blue-800 hover:bg-blue-50">Explore MeshNomics<ArrowUpRight className="h-5 w-5"/></ResourceLink><p className="mt-auto pt-8 text-sm leading-6 text-blue-200">MarketplaceBeta and MeshNomics share ownership. This is a companion-site link; no account, marketplace sales data, or machine data is transferred by this news desk.</p></div>
      </section>
      <section id="manufacturing-events" aria-labelledby="manufacturing-events-title" className="scroll-mt-44 border-t border-border py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="editorial-eyebrow">Meet the ecosystem</p><h2 id="manufacturing-events-title" className="mt-2 text-3xl font-bold">Events worth investigating.</h2></div><CalendarDays className="h-8 w-8 text-primary"/></div><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">Selected organizer-confirmed dates, including broader additive manufacturing events. Check the program, current dates, and exhibitor fit before planning a trip.</p><div className="mt-6 grid gap-6 md:grid-cols-2">{events.map(event=><article key={event.name} className="editorial-elevated rounded-2xl border border-border bg-card p-7"><p className="text-sm font-bold text-primary">{event.dates}</p><h3 className="mt-3 text-2xl font-bold">{event.name}</h3><p className="mt-2 font-medium">{event.location}</p><p className="mt-3 text-xs font-bold uppercase tracking-wider text-muted-foreground">{event.scope}</p><p className="mt-4 leading-7 text-muted-foreground">{event.note}</p><p className="mt-4 text-xs text-muted-foreground">Dates checked {formatDate(event.verifiedAt)} · Curated calendar</p><a href={event.url} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 font-bold text-primary">Organizer details<ArrowUpRight className="h-4 w-4"/></a></article>)}</div>{!events.length && <p className="mt-5 rounded-xl border border-border bg-card p-6">No future dated events are currently listed. Check the organizers’ calendars below for new announcements.</p>}<a href="https://makerfaire.com/upcoming-faires/" target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary">Explore the Maker Faire calendar<ArrowUpRight className="h-4 w-4"/></a></section>
      <section id="manufacturing-sources" aria-labelledby="manufacturing-sources-title" className="border-t border-border py-10"><p className="editorial-eyebrow">Know where it comes from</p><h2 id="manufacturing-sources-title" className="mt-2 text-3xl font-bold">The source directory.</h2><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">Manufacturer announcements tell you what the vendor says. Trade reporting adds context. Follow the original report before accepting a performance claim or changing your operating plan.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{MANUFACTURING_SOURCES.map(source=>{const status=snapshot.sources.find(s=>s.id===source.id);return <a key={source.id} href={source.url} target="_blank" rel="noopener noreferrer" className="editorial-elevated rounded-xl border border-border bg-card p-5 hover:border-primary/40"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{source.kind} · {source.process}</p><h3 className="mt-3 text-xl font-bold">{source.name} ↗</h3><p className="mt-3 text-sm text-muted-foreground">{!status?.available ? 'Feed unavailable in this snapshot · visit source' : `${status.count} eligible ${status.count === 1 ? 'report' : 'reports'} in this feed’s 90-day window`}</p></a>})}</div><h3 className="mt-10 text-2xl font-bold">Designs, releases, and operator communities.</h3><p className="mt-3 text-sm text-muted-foreground">Direct research links. These communities and model libraries are not scraped into this feed.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{resourceLinks.map(resource=><a key={resource.name} href={resource.url} target="_blank" rel="noopener noreferrer" className="rounded-xl border border-border bg-card p-6"><h4 className="text-lg font-bold text-primary">{resource.name} ↗</h4><p className="mt-3 text-sm leading-6 text-muted-foreground">{resource.detail}</p></a>)}</div><p className="mt-8 text-sm leading-6 text-muted-foreground">This desk links to publisher headlines rather than republishing full articles. Exact repeated headlines are grouped; related reporting may still appear separately. News is not a sales forecast. <Link href="/editorial-policy" className="text-primary underline">Read our editorial policy</Link>.</p></section>
    </main><PremiumSiteFooter/></div>
}
